apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: laravel-resourceful
  annotations:
    github.com/project-slug: yourparkingspace/laravel-resourceful
spec:
  type: service
  lifecycle: production
  owner: marketplace-backend
